# Generated by Django 2.2.6 on 2019-10-24 23:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0005_auto_20191013_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('label', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Reviewed'), (3, 'Published'), (4, 'Returned'), (5, 'Rejected'), (6, 'Draft')], default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='person.Person')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'knowledgebase_article',
                'ordering': ['-date_created'],
                'abstract': False,
                'unique_together': {('label',)},
            },
        ),
    ]
