# Generated by Django 2.2.6 on 2019-10-26 05:14

import apps.knowledgebase.models.models_abstract
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('person', '0006_auto_20191026_1214'),
        ('knowledgebase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Tertunda'), (2, 'Ditinjau'), (3, 'Terbit'), (4, 'Dikembalikan'), (5, 'Ditolak'), (6, 'Konsep')], default=1),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('value_image', models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.knowledgebase.models.models_abstract.directory_image_path)),
                ('value_file', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.knowledgebase.models.models_abstract.directory_file_path)),
                ('featured', models.BooleanField(null=True)),
                ('caption', models.TextField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(app_label='knowledgebase'), on_delete=django.db.models.deletion.CASCADE, related_name='knowledgebase_entity_attachment', to='contenttypes.ContentType')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledgebase_uploader', to='person.Person')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'db_table': 'knowledgebase_attachment',
                'ordering': ['-date_updated'],
                'abstract': False,
            },
        ),
    ]
