# Generated by Django 2.2.6 on 2019-10-29 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notice', '0005_auto_20191029_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content_notified',
        ),
        migrations.AddField(
            model_name='notification',
            name='content_notified_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_notified_type',
            field=models.ForeignKey(limit_choices_to=models.Q(app_label__in=['escort', 'person']), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice_entity_notified', to='contenttypes.ContentType'),
        ),
    ]
