# Generated by Django 2.2.6 on 2019-10-30 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notice', '0006_auto_20191029_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='object_id',
            new_name='content_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='content_source_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_source_type',
            field=models.ForeignKey(limit_choices_to=models.Q(app_label__in=['escort', 'person']), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice_entity_source', to='contenttypes.ContentType'),
        ),
    ]
