# Generated by Django 2.2.6 on 2019-10-30 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0008_auto_20191030_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content_parent_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content_parent_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(app_label__in=['escort', 'person']), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice_entity_notification_parent', to='contenttypes.ContentType'),
        ),
    ]
