# Generated by Django 2.2.6 on 2019-10-08 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escort', '0002_auto_20191008_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escort_model_attachment', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='content_type',
            field=models.ManyToManyField(blank=True, related_name='escort_attibute', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='content_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escort_model_attibutes', to='contenttypes.ContentType'),
        ),
    ]
