# Generated by Django 2.2.6 on 2019-10-13 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escort', '0004_auto_20191008_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escort_model_attibutes', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
