# Generated by Django 2.2.6 on 2019-10-17 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20191013_1123'),
        ('escort', '0005_auto_20191013_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploader', to='person.Person'),
        ),
    ]
