# Generated by Django 2.2.6 on 2019-10-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escort', '0006_attachment_uploader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-date_updated'], 'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AddField(
            model_name='attachment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
