# Generated by Django 2.2.6 on 2019-10-17 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escort', '0007_auto_20191017_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentattachment',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='protestattachment',
            name='featured',
        ),
    ]
