# Generated by Django 2.2.6 on 2019-10-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escort', '0008_auto_20191017_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaattachment',
            name='media',
        ),
        migrations.RemoveField(
            model_name='protestattachment',
            name='protest',
        ),
        migrations.DeleteModel(
            name='CommentAttachment',
        ),
        migrations.DeleteModel(
            name='MediaAttachment',
        ),
        migrations.DeleteModel(
            name='ProtestAttachment',
        ),
    ]
