# Generated by Django 2.2.6 on 2019-10-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escort', '0009_auto_20191017_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='protestthumb',
            name='thumbing',
            field=models.NullBooleanField(),
        ),
    ]
