# Generated by Django 2.2.6 on 2019-10-21 01:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('person', '0005_auto_20191013_1123'),
        ('escort', '0010_protestthumb_thumbing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('thumbing', models.NullBooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escort_thumbed', to='contenttypes.ContentType')),
                ('thumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumber', to='person.Person')),
            ],
            options={
                'verbose_name': 'Thumbed',
                'verbose_name_plural': 'Thumbeds',
                'db_table': 'escort_thumbed',
                'abstract': False,
                'unique_together': {('thumber', 'content_type', 'object_id')},
            },
        ),
        migrations.AlterField(
            model_name='entitylog',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escort_entity_attibutes', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='entitylog',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='ProtestThumb',
        ),
    ]
