# Generated by Django 2.2.6 on 2019-10-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escort', '0011_auto_20191021_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date_created',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
