# Generated by Django 2.2.6 on 2019-10-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escort', '0012_auto_20191023_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='classification',
            field=models.PositiveIntegerField(choices=[(1, 'Electronic'), (2, 'Printed'), (3, 'Online')], default=1),
        ),
        migrations.DeleteModel(
            name='Classification',
        ),
    ]
