# Generated by Django 2.2.6 on 2019-10-26 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escort', '0015_auto_20191024_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(app_label='escort'), on_delete=django.db.models.deletion.CASCADE, related_name='escort_entity_attachment', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='content_type',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(app_label='escort'), related_name='escort_attibute', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(app_label='escort'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escort_model_attibutes', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='entitylog',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(app_label='escort'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escort_entity_attibutes', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='entitylog',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Tertunda'), (2, 'Ditinjau'), (3, 'Terbit'), (4, 'Dikembalikan'), (5, 'Ditolak'), (6, 'Konsep')], default=1),
        ),
        migrations.AlterField(
            model_name='media',
            name='classification',
            field=models.PositiveIntegerField(choices=[(1, 'Elektronik'), (2, 'Cetak'), (3, 'Online')]),
        ),
        migrations.AlterField(
            model_name='media',
            name='publication',
            field=models.PositiveIntegerField(choices=[((1, 'Elektronik'), ((1, 'Televisi'), (2, 'Radio'))), ((3, 'Online'), ((3, 'YouTube'), (4, 'Sosial Media'), (5, 'Blog'), (6, 'Situs Berita'))), ((2, 'Cetak'), ((7, 'Koran'), (8, 'Majalah')))]),
        ),
        migrations.AlterField(
            model_name='media',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Tertunda'), (2, 'Ditinjau'), (3, 'Terbit'), (4, 'Dikembalikan'), (5, 'Ditolak'), (6, 'Konsep')], default=1),
        ),
        migrations.AlterField(
            model_name='protest',
            name='purpose',
            field=models.PositiveIntegerField(choices=[(1, 'Tidak Benar'), (2, 'Kritik dan Saran'), (3, 'Diskusi')], default=3),
        ),
        migrations.AlterField(
            model_name='protest',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Tertunda'), (2, 'Ditinjau'), (3, 'Terbit'), (4, 'Dikembalikan'), (5, 'Ditolak'), (6, 'Konsep')], default=1),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveIntegerField(choices=[(1, 'Terburuk'), (2, 'Buruk'), (3, 'Sedang'), (4, 'Baik'), (5, 'Sangat Baik')]),
        ),
        migrations.AlterField(
            model_name='thumbed',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(app_label='escort'), on_delete=django.db.models.deletion.CASCADE, related_name='escort_thumbed', to='contenttypes.ContentType'),
        ),
    ]
