# Generated by Django 2.2.6 on 2019-10-27 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20191026_1214'),
        ('escort', '0016_auto_20191026_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_for_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_for', to='person.Person'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_to', to='escort.Comment', verbose_name='Reply yo comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='escort.Comment', verbose_name='Parent comment'),
        ),
    ]
