# Generated by Django 2.2.6 on 2019-10-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escort', '0017_auto_20191027_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_for_person',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to_comment',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
