# Generated by Django 2.2.6 on 2019-10-27 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escort', '0018_auto_20191027_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_for_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_for', to='person.Person'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_to', to='escort.Comment', verbose_name='Reply yo comment'),
        ),
    ]
