# Generated by Django 2.2.6 on 2019-10-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escort', '0020_auto_20191028_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='value_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('url', 'URL'), ('integer', 'Integer'), ('boolean', 'True / False'), ('float', 'Float'), ('richtext', 'Rich Text'), ('date', 'Date'), ('datetime', 'Datetime'), ('option', 'Option'), ('multi_option', 'Multi Option'), ('file', 'File'), ('image', 'Image')], default='text', max_length=20, verbose_name='Type'),
        ),
    ]
