# Generated by Django 2.2.6 on 2019-11-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escort', '0022_auto_20191105_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='instruction',
            field=models.TextField(blank=True, null=True, verbose_name='Instruction'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='placeholder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='secured',
            field=models.BooleanField(default=False, verbose_name='Secured'),
        ),
    ]
