# Generated by Django 2.2.6 on 2019-10-08 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'verbose_name': 'Attribute value', 'verbose_name_plural': 'Attribute values'},
        ),
        migrations.RenameField(
            model_name='attributevalue',
            old_name='entity_id',
            new_name='object_id',
        ),
        migrations.AddField(
            model_name='attribute',
            name='content_type',
            field=models.ManyToManyField(blank=True, related_name='person_attibute', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='content_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_model_attibutes', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='option_group',
            field=models.ForeignKey(blank=True, help_text='Select option group if using type "Option" or "Multi Option"', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_attributes', to='person.AttributeOptionGroup', verbose_name='Option Group'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('url', 'URL'), ('integer', 'Integer'), ('boolean', 'True / False'), ('float', 'Float'), ('richtext', 'Rich Text'), ('date', 'Date'), ('datetime', 'Datetime'), ('option', 'Option'), ('multi_option', 'Multi Option'), ('file', 'File'), ('image', 'Image')], default='text', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'content_type', 'object_id')},
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='entity_content_type',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='person',
        ),
    ]
