# Generated by Django 2.2.6 on 2019-10-08 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20191008_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='content_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_entity_attibutes', to='contenttypes.ContentType'),
        ),
    ]
