# Generated by Django 2.2.6 on 2019-10-26 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20191013_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='content_type',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(app_label='person'), related_name='person_attibute', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(app_label='person'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_entity_attibutes', to='contenttypes.ContentType'),
        ),
    ]
