# Generated by Django 2.2.6 on 2019-10-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_auto_20191031_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='method',
            field=models.IntegerField(choices=[(1, 'Auto'), (0, 'Manual')], help_text='Verification method', null=True),
        ),
    ]
