# Generated by Django 2.2.6 on 2019-11-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_validation_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationvalue',
            name='verified',
            field=models.BooleanField(null=True),
        ),
    ]
