# Generated by Django 2.2.6 on 2019-11-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_validationvalue_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationvalue',
            name='secure_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
