# Generated by Django 2.2.6 on 2019-11-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_auto_20191104_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='validationvalue',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='validationvalue',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
